"""Finite Map Patterns (FMP): a readable experimental definition kernel.

Columns/points start at one.  A nonempty column at r is an increasing
finite map ending in p->r and e->r+1; completed patterns have e=p+1.
Every target below p is also a source (self-closure).  Internal starred
edges have targets at least e and accurate traces through earlier pivots.
The standard domain is generated by the compatible seeds at the bottom.

When copying a source column with an unavailable referenced point, retain
its point but leave its map empty.  The controller's self-copy is always
available, by self-closure.  Empty columns are successor suffixes.

No semantic oracle or resource threshold occurs in the mathematical rules.
Applications may pass a check callback; its exceptions mean UNKNOWN, not
an alternative fundamental-sequence value.  See the companion documents
for the proof route, conditions, and limits of the strength claims.
"""

from dataclasses import dataclass


@dataclass(frozen=True)
class Column:
    edges: tuple[tuple[int, int], ...] = ()
    stars: frozenset[int] = frozenset()

    @property
    def minimum(self):
        return self.edges[0][0]

    @property
    def pivot(self):
        return self.edges[-2][0]

    def relabel(self, image):
        return Column(tuple((image(x), image(y)) for x, y in self.edges),
                      frozenset(image(y) for y in self.stars))


@dataclass(frozen=True)
class Pattern:
    columns: tuple[Column, ...] = ()

    def cut(self):
        return Pattern(self.columns[:-1])

    def expand(self, index, check=lambda *_: None):
        if not isinstance(index, int) or index < 0:
            raise ValueError('the fundamental-sequence index must be natural')
        if not self.columns:
            return self
        if index == 0 or not self.columns[-1].edges:
            return self.cut()
        work = self
        for _ in range(index):
            check(2 * len(work.columns) - work.columns[-1].pivot)
            work = copy_tail(work)
        # Cut the actual last self-copy BEFORE creating restriction families.
        return complete(work.cut(), len(self.columns), check)

    __getitem__ = expand


def trace(columns, head, source):
    """The nonterminal vertices of an exact decreasing pivot trace."""
    path = []
    while head > source:
        path.append(head)
        column = columns[head - 1]
        if not column.edges:
            return ()
        head = column.pivot
    return tuple(path) if head == source else ()


def copy_tail(pattern):
    """Retain the prefix and copy the tail, forgetting unavailable maps."""
    columns = pattern.columns
    size = len(columns)
    controller = columns[-1]
    minimum, pivot = controller.minimum, controller.pivot
    table = dict(controller.edges)

    def image(x):
        if x < minimum:
            return x
        return x + size - pivot if x >= pivot else table[x]

    result = list(columns[:-1])
    for column in columns[pivot - 1:]:
        try:
            edges = tuple((image(x), image(y)) for x, y in column.edges)
        except KeyError:
            result.append(Column())
            continue
        stars = set()
        for j, (source, head) in enumerate(column.edges):
            if head not in column.stars:
                continue
            path = trace(columns, head, source)
            if not path:
                continue
            if path[-1] >= pivot:
                keep = True
            else:
                low = next(v for v in path if v < pivot)
                keep = (low < minimum or
                        (low in table and image(low) in controller.stars and
                         edges[j + 1][0] <= minimum))
            if keep and trace(result, image(head), image(source)):
                stars.add(image(head))
        result.append(Column(edges, frozenset(stars)))
    return Pattern(tuple(result))


def complete(pattern, start, check=lambda *_: None):
    """One forward scan, skipping columns created during this scan.

    A record stores only a width.  All its sources are consecutive points.
    First propagate the entrance-old stars, then split the last source gap.
    """
    columns = list(pattern.columns)
    widths = {}
    r = start
    while r <= len(columns):
        check(len(columns))
        column = columns[r - 1]
        if not column.edges:
            r += 1
            continue
        table, stars = dict(column.edges), set(column.stars)
        sources = {y: x for x, y in column.edges}
        for head in sorted(column.stars):
            source = sources[head]
            path = trace(columns, head, source)
            width = widths.get(path[-1], 0) if path else 0
            for j in range(1, width + 1):
                table[source + j] = head + j
                stars.add(head + j)
        column = Column(tuple(sorted(table.items())), frozenset(stars))
        columns[r - 1] = column

        pivot, endpoint = column.edges[-2][0], column.edges[-1][0]
        width = endpoint - pivot - 1
        if width:
            check(len(columns) + width)
            shift = lambda x: x + width if x > r else x
            for i in range(r, len(columns)):
                columns[i] = columns[i].relabel(shift)
            widths[r] = width
            edges = (column.edges[:-1] +
                     tuple((pivot + j, r + j) for j in range(1, width + 1)) +
                     ((endpoint, r + width + 1),))
            family = []
            for j in range(width + 1):
                lower = tuple(edge for edge in edges if edge[0] <= pivot + j + 1)
                marks = column.stars | frozenset(range(r, r + j))
                family.append(Column(lower, marks))
            columns[r - 1:r] = family
        r += width + 1
    return Pattern(tuple(columns))


def seed(n):
    """Nested I3-realizable roots; all initial stars are empty.

    An empty point and one unit shift, followed at each stage by another
    unit shift and its square; their common critical point advances by two.
    """
    if not isinstance(n, int) or n < 0:
        raise ValueError('the seed index must be natural')
    columns = [Column(), Column(((1, 2), (2, 3)))]
    for i in range(n):
        minimum = 2 * i + 1
        for step in (1, 2):
            r = len(columns) + 1
            edges = tuple((x, x + step) for x in range(minimum, r - step + 2))
            columns.append(Column(edges))
    return Pattern(tuple(columns))
